'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SkyeTools.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend Shared ReadOnly Property iconApp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("iconApp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend Shared ReadOnly Property IconHelp() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("IconHelp", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend Shared ReadOnly Property iconLog() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("iconLog", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend Shared ReadOnly Property iconSettings() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("iconSettings", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend Shared ReadOnly Property iconWL() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("iconWL", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend Shared ReadOnly Property IconWST() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("IconWST", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend Shared ReadOnly Property IconWSTAlert() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("IconWSTAlert", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend Shared ReadOnly Property IconWSTSS() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("IconWSTSS", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend Shared ReadOnly Property IconWSTSSDisabled() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("IconWSTSSDisabled", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imageAC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageAC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ImageAC16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageAC16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ImageAC48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageAC48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imageACClock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageACClock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imageACDefaultChime() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageACDefaultChime", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imageACFolder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageACFolder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imageACMute() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageACMute", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imageACPlay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageACPlay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imageACSound() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageACSound", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imageApp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageApp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ImageApp32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageApp32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imageClose() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageClose", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imageCopy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageCopy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ImageDeleteLog32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageDeleteLog32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imageEdit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageEdit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ImageError16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageError16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ImageError32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageError32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ImageFolder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageFolder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imageGoReStart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageGoReStart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imageGoStart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageGoStart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ImageHC16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageHC16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ImageHC48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageHC48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imageHK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageHK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ImageHK48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageHK48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imageHKDisable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageHKDisable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imageHKEnable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageHKEnable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ImageInfo16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageInfo16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imageInfo32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageInfo32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imageLog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageLog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ImageLog32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageLog32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imageMoveDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageMoveDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imageMoveToBottom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageMoveToBottom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imageMoveToTop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageMoveToTop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imageMoveUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageMoveUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ImageOK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageOK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ImageOK16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageOK16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imageRemove() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageRemove", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imageRestore() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageRestore", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imageSave() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageSave", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ImageSave16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageSave16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ImageSave32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageSave32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imageSelectAll() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageSelectAll", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imageSettings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageSettings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ImageSize16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageSize16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imageSwap() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageSwap", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imageTextCopy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageTextCopy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imageTextCut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageTextCut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imageTextPaste() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageTextPaste", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imageTextRedo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageTextRedo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imageTextUndo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageTextUndo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ImageUndo16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageUndo16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ImageUndo32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageUndo32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imageWindowHide() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageWindowHide", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imageWindowMaximize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageWindowMaximize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imageWindowRestore() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageWindowRestore", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imageWL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageWL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ImageWL48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageWL48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imageWLNew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageWLNew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ImageWST16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageWST16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ImageWST48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageWST48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ImageWSTClock16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageWSTClock16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ImageWSTClock48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageWSTClock48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imageWSTSessionKey() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imageWSTSessionKey", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ImageWSTSS16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageWSTSS16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ImageWSTSS48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageWSTSS48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ImageWSTSSDisabled16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageWSTSSDisabled16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ImageWSTSSDisabled48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageWSTSSDisabled48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property soundChime() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("soundChime", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
